import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require('playwright');
const dir='/data/recordcheck/qa';await mkdir(dir,{recursive:true});
const browser=await chromium.launch({executablePath:execFileSync('which',['chromium'],{encoding:'utf8'}).trim(),headless:true,args:['--no-sandbox']});
const checks=[],errors=[],externalRequests=[];
let page;
try{
 page=await browser.newPage({viewport:{width:1366,height:1000},colorScheme:'light',acceptDownloads:true});
 page.on('pageerror',err=>errors.push(err.message));page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('favicon'))errors.push(m.text());});page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:4173')&&!r.url().startsWith('blob:')&&!r.url().startsWith('file:'))externalRequests.push(r.url());});page.on('dialog',d=>d.accept());
 const waitReady=()=>page.waitForFunction(()=>{const el=document.getElementById('messages');return !!el&&!el.textContent.includes('Checking references and computing');});
 await page.goto('http:'+'//127.0.0.1:4173/',{waitUntil:'networkidle'});await waitReady();
 assert(await page.getByRole('heading',{name:'A citation is not a verification.'}).isVisible());checks.push('Desktop app starts and completes core checks');
 assert(await page.locator('.signals').textContent().then(s=>s.includes('SGD 18000')));checks.push('Real amount/quote flags render with source lines');
 await page.screenshot({path:dir+'/desktop-review.png',fullPage:true});
 await page.locator('[data-claim="C3"]').click();await page.locator('input[name="reviewer"]').fill('QA reviewer');await page.locator('textarea[name="reason"]').fill('Read exact source and surrounding context for this synthetic payment.');await page.locator('input[name="ack"]').check();await page.getByRole('button',{name:'Record disposition'}).click();assert(await page.locator('.review-detail .badge').textContent().then(s=>s.includes('Reviewed')));checks.push('Human review records only after reason and acknowledgement');
 await page.screenshot({path:dir+'/reviewed.png',fullPage:true});
 await page.getByRole('button',{name:'Matter data',exact:true}).click();await page.locator('summary').filter({hasText:'E3 ·'}).click();const doc=page.locator('form[data-doc="E3"] textarea');await doc.fill((await doc.inputValue())+'\nAdditional source context.');await page.locator('form[data-doc="E3"] button').click();await waitReady();await page.getByRole('button',{name:'Review claims',exact:true}).click();await page.locator('[data-claim="C3"]').click();assert(await page.locator('.review-detail .badge').textContent().then(s=>s.includes('stale')));checks.push('Changing full source invalidates old review in actual UI');await page.screenshot({path:dir+'/stale.png',fullPage:true});
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export review packet'}).click();const dl=await downloadPromise;await dl.saveAs(dir+'/exported-review-packet.md');checks.push('Download creates a real Markdown review packet');
 await page.locator('[data-claim="C6"]').click();assert(await page.locator('.uncertain').textContent().then(s=>s.includes('claim supported')));checks.push('Semantic counterexample still requires human review');
 await page.getByRole('button',{name:'Matter data',exact:true}).click();await page.locator('#json-input').fill('{broken');await page.getByRole('button',{name:'Validate & import'}).click();assert(await page.getByRole('alert').textContent().then(s=>s.includes('Invalid JSON')));checks.push('Invalid JSON produces a visible safe error without replacing matter');await page.screenshot({path:dir+'/error.png',fullPage:true});
 await page.getByRole('button',{name:'Review activity',exact:true}).click();await page.screenshot({path:dir+'/activity.png',fullPage:true});
 await page.getByRole('button',{name:'Scope & limitations',exact:true}).click();await page.screenshot({path:dir+'/limits.png',fullPage:true});
 // A real import with an XSS-like title must remain literal and initiate no requests.
 const {demoMatter}=await import('../src/core.ts');const hostile=demoMatter();hostile.title='<img src="https://example.invalid/leak" onerror="window.PWNED=1">';await page.getByRole('button',{name:'Matter data',exact:true}).click();await page.locator('#json-input').fill(JSON.stringify(hostile));await page.getByRole('button',{name:'Validate & import'}).click();await waitReady();assert.equal(await page.evaluate(()=>globalThis.PWNED),undefined);assert.equal(await page.locator('img').count(),0);checks.push('Imported HTML remains inert text (no element or request)');
 await page.getByRole('button',{name:'Review activity',exact:true}).click();assert(!(await page.locator('.activity').textContent()).includes('Changed source E3'));checks.push('Replacing a matter clears earlier matter activity and reviews');await page.getByRole('button',{name:'Matter data',exact:true}).click();
 await page.getByRole('button',{name:'Clear this local matter'}).click();await waitReady();await page.getByRole('button',{name:'Review claims',exact:true}).click();assert(await page.getByRole('heading',{name:'No claims yet'}).isVisible());checks.push('Empty matter does not become a completed handoff');await page.screenshot({path:dir+'/empty.png',fullPage:true});
 await page.getByRole('button',{name:'Reset synthetic demo'}).click();await waitReady();await page.setViewportSize({width:390,height:844});await page.screenshot({path:dir+'/mobile-review.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('390px mobile layout has no horizontal overflow');
 await page.getByRole('button',{name:'Matter data',exact:true}).click();await page.screenshot({path:dir+'/mobile-data.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('390px import/source-edit layout has no horizontal overflow');
 await page.setViewportSize({width:1366,height:1000});await page.emulateMedia({colorScheme:'dark'});await page.getByRole('button',{name:'Review claims',exact:true}).click();await page.screenshot({path:dir+'/dark-review.png',fullPage:true});checks.push('Dark theme renders');
 assert.equal(await page.evaluate(()=>localStorage.length),0);assert.equal(await page.evaluate(()=>sessionStorage.length),0);checks.push('No localStorage/sessionStorage persistence');
 await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement?.tagName!=='BODY'));checks.push('Keyboard focus reaches an interactive control');
 assert.equal(externalRequests.length,0);assert.equal(errors.length,0);checks.push('Zero external requests and zero browser errors in tested flows');
 await page.goto('http:'+'//127.0.0.1:4173/index.html',{waitUntil:'networkidle'});await waitReady();checks.push('Direct index.html deep link loads');
 await page.goto('http://127.0.0.1:4173/build-info.json');const info=JSON.parse(await page.locator('body').textContent());assert(info.sha256);checks.push('Local build metadata is accessible');
 await page.goto(new URL('../dist/index.html',import.meta.url).href);await waitReady();assert((await page.locator('.signals').textContent()).includes('SGD 18000'));checks.push('Self-contained HTML works directly from a local file');await page.waitForTimeout(100);assert.equal(externalRequests.length,0);assert.equal(errors.length,0);const result={at:new Date().toISOString(),checks,passed:checks.length,browserErrors:errors,externalRequests,screenshots:'qa/*.png',scope:'Local Chromium E2E only; no remote deployment, no Gemini path',visualInspection:'PENDING separate image inspection'};await writeFile('docs/qa-results.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(err){await writeFile('docs/qa-results.json',JSON.stringify({passed:checks.length,checks,error:String(err),browserErrors:errors,externalRequests},null,2));console.error(err);process.exitCode=1;}finally{if(page)await page.close();await browser.close();}
